# Generated by Django 3.0.7 on 2021-11-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211129_2232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
